### ISSUE TITLE
Broken semver

### ISSUE THREAD

**Issue by MattSurabian** [MattSurabian/aes-gcm-stream#9]
When I merged #4 I should have cut 2.0.0 NOT 1.1.0 because switching where the MAC is located is a breaking change for users of 1.0.0. 

Fix is to cut 1.1.2 which will be identical to 1.0.0. Deprecate 1.1.1 and 1.1.0 on npm, then cut a new 2.0.0 release based on master.

Bleh.

**Comment by calvinmetcalf** [comment]
dude just unpublish 1.1.0 and republish as 2.0.0

**Comment by MattSurabian** [comment]
I thought unpublish wasn't actually allowed anymore

**Comment by calvinmetcalf** [comment]
nope, what isn't alowed is to republish with the same version number

**Comment by MattSurabian** [comment]
This mess is cleaned up. Thanks to @calvinmetcalf and @leobalter for reminding me unpublish was still allowed before I went too far down this rabbit hole. 

I'm going to be more careful when cutting versions next time.

:fire:
